# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric color
format 5 = "%F"
format A 10 0 5
format B 7 2 0
format C 7 2 0
color 1 = @white;@black
color 7 = @white;@blue
rightstring A0 = "date"
rightstring B0 = "cost"
rightstring C0 = "total"
let A1 = @dts(2015,12,1)
let B1 = 40
let C1 = B1
goto B1 A0
